In [196]:
import pandas as pd

In [197]:
import tensorflow as tf

In [198]:
import keras

In [199]:
banking_data = pd.read_csv('D:/Evarcity/R-Programming/bank-full.csv', sep =';')

In [200]:
banking_data

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

In [201]:
## Step1: Depedent variable is non numeric convert into numeric
import numpy as np

banking_data['y']=np.where(banking_data.y=='no',0,1)

## banking_data.y = banking_data.y.replace({'yes':1, 'no':0})

In [202]:
## Step2: Get all the indepedent variables

x=banking_data.drop('y', axis=1)

In [203]:
## Step3: Get depedent variable

y = banking_data['y']

In [204]:
## Strp 4 : Convert non numeric indepedent variable to numeric
x= pd.get_dummies(x)

In [205]:
## Step5: Divide the data into traing and test set

from sklearn.model_selection import train_test_split

In [206]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.20)

In [207]:
## Building a tensorflow model

x=x.values

In [208]:
print(x)

[[  58 2143    5 ...    0    0    1]
 [  44   29    5 ...    0    0    1]
 [  33    2    5 ...    0    0    1]
 ...
 [  72 5715   17 ...    0    1    0]
 [  57  668   17 ...    0    0    1]
 [  37 2971   17 ...    1    0    0]]


In [209]:
## convert y into numpy arrays

y=y.values

In [210]:
print(y)

[0 0 0 ... 1 0 0]


In [211]:
from sklearn.preprocessing import StandardScaler

In [212]:
sc = StandardScaler()

In [213]:
xtrain =sc.fit_transform(xtrain)

In [214]:
xtest = sc.transform(xtest)

In [215]:
## import libraries for deep learning

import tensorflow as tf

import keras

In [216]:
from keras.models import Sequential

In [217]:
from keras.layers import Dense

In [218]:
## We will define a model

model = Sequential()

In [219]:
## Add layer in the neural network (Hidden Layer)

model.add(Dense(20, kernel_initializer='uniform',activation ='relu', input_dim=51))

## 20 - num of nodes, kernel_initializer = to calulate optimum weight

In [220]:
## Add layer in the neural network (Output Layer)

model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))

##1, number of output

In [221]:
## Complile the model

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

## 'adam' - optimizer algorithm

In [222]:
## fit the model
model.fit(xtrain, ytrain, batch_size=10, epochs=10)

Epoch 1/10
3617/3617 [==============================] - 11s 3ms/step - loss: 0.2412 - accuracy: 0.9000
Epoch 2/10
3617/3617 [==============================] - 9s 3ms/step - loss: 0.2110 - accuracy: 0.9063
Epoch 3/10
3617/3617 [==============================] - 9s 3ms/step - loss: 0.2063 - accuracy: 0.9085
Epoch 4/10
3617/3617 [==============================] - 10s 3ms/step - loss: 0.2037 - accuracy: 0.9089
Epoch 5/10
3617/3617 [==============================] - 9s 2ms/step - loss: 0.2016 - accuracy: 0.9091
Epoch 6/10
3617/3617 [==============================] - 10s 3ms/step - loss: 0.2003 - accuracy: 0.9111
Epoch 7/10
3617/3617 [==============================] - 10897s 3s/step - loss: 0.1991 - accuracy: 0.9112
Epoch 8/10
3617/3617 [==============================] - 10934s 3s/step - loss: 0.1980 - accuracy: 0.9116
Epoch 9/10
3617/3617 [==============================] - 10s 3ms/step - loss: 0.1967 - accuracy: 0.9130
Epoch 10/10
3617/3617 [==============================] - 8s 2ms/step - l

In [223]:
## batch size = the numbers of samples that will go through neural n/w in each training round

## epochs = the number of times that the dataset will pass through neutal n/w.

In [224]:
## apply the model into testset

pred_value = model.predict(xtest)

283/283 [==============================] - 0s 1ms/step


In [225]:
## convert the vlaues to 0 for value<0.5 and 1 for 0 > 
pred_value_bin = np.where(pred_value>0.5,1,0)

In [226]:
pred_value_bin

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [227]:
#### Validation to xtest and ytest using confusion matrix
import sklearn.metrics as metrics


In [228]:
confusion_matrix = metrics.confusion_matrix(ytest, pred_value)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [ ]:
## Calculate Precison. we used po

from sklearn.metrics import precision_score
precision = precision_score(ytest, pred_value_binary, pos_label=1)
print(precision)

In [ ]:
## Calcualte Recall/Sensitivity

from sklearn.metrics import recall_score
recall_score = recall_score(ytest, pred_value_binary, pos_label=1)
print(recall_score)

In [ ]:
## Calculate F1_Score

from sklearn.metrics import f1_score
f1_score = f1_score(ytest, pred_value_binary, pos_label=1)
print(f1_score)