In [1]:
import pandas as pd

In [2]:
import numpy as np

In [14]:
import os

In [15]:
os.getcwd()

'C:\\Users\\Rajz'

In [3]:
titanic_data = pd.read_csv('D:/Evarcity/R-Programming/titanic.csv')

In [4]:
titanic_data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [43]:
## to know the status of missing values  

titanic_data.isnull().any()


PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [44]:
## to know the msissing values in counts

titanic_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [45]:
## Check missing values in percentage

titanic_data.isnull().sum()/len(titanic_data)*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [46]:
## checking missing values using lambda function

titanic_data.apply(lambda x:x.isnull().sum()/len(x)*100)

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [5]:
## Get all the numeric in a dataset

data1 = titanic_data.select_dtypes(include=np.number)

In [52]:
data1.head()

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0            1         0       3  22.0      1      0   7.2500
1            2         1       1  38.0      1      0  71.2833
2            3         1       3  26.0      0      0   7.9250
3            4         1       1  35.0      1      0  53.1000
4            5         0       3  35.0      0      0   8.0500

In [53]:
from sklearn import preprocessing as p

In [55]:
### Convert all values b/w 0and 1, but the weightage of the value in that column should not change

min_max_scaler = p.MinMaxScaler()

normalizedata = min_max_scaler.fit_transform(data1)

In [56]:
print(normalizedata)

[[0.         0.         1.         ... 0.125      0.         0.01415106]
 [0.0011236  1.         0.         ... 0.125      0.         0.13913574]
 [0.00224719 1.         1.         ... 0.         0.         0.01546857]
 ...
 [0.99775281 0.         1.         ... 0.125      0.33333333 0.04577135]
 [0.9988764  1.         0.         ... 0.         0.         0.0585561 ]
 [1.         0.         1.         ... 0.         0.         0.01512699]]


In [6]:
### Convert all values b/w 0and 1, but the weightage of the value in that column should not change using lambda function

data1.apply(lambda x:x/x.sum())

PassengerId  Survived    Pclass       Age     SibSp     Parch      Fare
0       0.000003  0.000000  0.001458  0.001037  0.002146  0.000000  0.000253
1       0.000005  0.002924  0.000486  0.001792  0.002146  0.000000  0.002484
2       0.000008  0.002924  0.001458  0.001226  0.000000  0.000000  0.000276
3       0.000010  0.002924  0.000486  0.001651  0.002146  0.000000  0.001851
4       0.000013  0.000000  0.001458  0.001651  0.000000  0.000000  0.000281
..           ...       ...       ...       ...       ...       ...       ...
886     0.002232  0.000000  0.000972  0.001273  0.000000  0.000000  0.000453
887     0.002235  0.002924  0.000486  0.000896  0.000000  0.000000  0.001046
888     0.002237  0.000000  0.001458       NaN  0.002146  0.005882  0.000817
889     0.002240  0.002924  0.000486  0.001226  0.000000  0.000000  0.001046
890     0.002242  0.000000  0.001458  0.001509  0.000000  0.000000  0.000270

[891 rows x 7 columns]

In [60]:
## To replace missing values in "Age"
m1 = titanic_data.Age.mean()
m1 = titanic_data['Age'] = titanic_data.Age.fillna(m1)

In [75]:
## Relace Emarked value with mode

titanic_data.Embarked.value_counts()

## to get max values in Embarked column 

titanic_data.Embarked.value_counts().idxmax()

'S'

In [7]:
titanic_data['Embarked'] = titanic_data.Embarked.fillna('S')